x-app-base: &app-base
  build:
    context: .
  env_file:
    - .env
  ports:
    - "8000:8000"
  depends_on:
    db:
      condition: service_healthy
  networks:
    - dev-app-network

x-app-env: &app-env
  DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
  DB_SHOULD_MIGRATE: "true"
  SESSION_TOKEN_SECRET_KEY: secret_key
  SESSION_TOKEN_DURATION: 24h
  BREVO_API_KEY: ${BREVO_API_KEY}
  EMAIL_SENDER_ADDRESS: ${EMAIL_SENDER_ADDRESS}
  SERVER_ADMIN_EMAIL: "admin@admin.admin"
  SERVER_ADMIN_PASSWORD: admin123
  STRIPE_API_KEY: ${STRIPE_API_KEY}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

x-stripe-base: &stripe-base
  image: stripe/stripe-cli:latest
  environment:
    STRIPE_API_KEY: ${STRIPE_API_KEY}
    STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
  networks:
    - dev-app-network

services:
  app-dev:
    <<: *app-base
    profiles: ["dev"]
    environment:
      <<: *app-env
    build:
      context: .
      target: dev
    tty: true
    volumes:
      - .:/usr/src/app

  app-prod:
    <<: *app-base
    profiles: ["prod"]
    environment:
      <<: *app-env
      SERVER_ENVIRONMENT: development
    build:
      context: .
      target: prod
    volumes:
      - ./local_buckets:/usr/src/app/local_buckets

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - dev-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  buckets:
    image: python:3.12-alpine
    init: true
    command: ["python", "-m", "http.server", "8000"]
    working_dir: /buckets
    ports:
      - "8081:8000"
    networks:
      - dev-app-network
    volumes:
      - ./local_buckets:/buckets

  stripe-payments-dev:
    <<: *stripe-base
    profiles: ["dev"]
    command: listen --forward-to app-dev:8000/payments/webhook/stripe

  stripe-payments-prod:
    <<: *stripe-base
    profiles: ["prod"]
    command: listen --forward-to app-prod:8000/payments/webhook/stripe

  stripe-subscriptions-dev:
    <<: *stripe-base
    profiles: ["dev"]
    command: listen --forward-to app-dev:8000/payments/webhook/stripe/subscriptions

  stripe-subscriptions-prod:
    <<: *stripe-base
    profiles: ["prod"]
    command: listen --forward-to app-prod:8000/payments/webhook/stripe/subscriptions

networks:
  dev-app-network:
    driver: bridge

volumes:
  db-data:
