services:
  app:
    build:
      context: .
      target: test
    tty: true
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=test_db
      - DB_PORT=5432
      - DB_NAME=postgres
    depends_on:
      test_db:
        condition: service_healthy
    networks:
      - app-network
  test_db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
