services:
  app:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=prod_db
      - DB_PORT=5432
      - DB_NAME=postgres
      - SESSION_TOKEN_SECRET_KEY=prod_secret_key
      - SESSION_TOKEN_DURATION=1h
    depends_on:
      prod_db:
        condition: service_healthy
    networks:
      - prod-app-network
  prod_db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - prod-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
networks:
  prod-app-network:
    driver: bridge
volumes:
  db-data:
