// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets/sprites": {
            "put": {
                "description": "Uploads a sprite file.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets-service"
                ],
                "summary": "UploadSpriteData",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Sprite file",
                        "name": "sprite",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Uploaded sprite",
                        "schema": {
                            "$ref": "#/definitions/dtos.SpriteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request body",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/sprites/categories": {
            "get": {
                "description": "Retrieves the list of existing categories UUIDs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets-service"
                ],
                "summary": "GetCategoriesList",
                "responses": {
                    "200": {
                        "description": "Category list",
                        "schema": {
                            "$ref": "#/definitions/dtos.SpriteCategoryListResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new sprite category.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets-service"
                ],
                "summary": "AddCategory",
                "parameters": [
                    {
                        "description": "Category data",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.AddSpriteCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created category",
                        "schema": {
                            "$ref": "#/definitions/dtos.SpriteCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request body",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/sprites/categories/{category_id}": {
            "get": {
                "description": "Retrieves the list of existing sprites UUIDs for a given category UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets-service"
                ],
                "summary": "GetSpritesListByCategory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category UUID",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sprite list",
                        "schema": {
                            "$ref": "#/definitions/dtos.SpritesListResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/sprites/{sprite_id}": {
            "get": {
                "description": "Downloads the sprite file for a given sprite UUID.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "assets-service"
                ],
                "summary": "DownloadSpriteData",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sprite UUID",
                        "name": "sprite_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sprite file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Log in an existing user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication-service"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginAccountRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login",
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginAccountResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request body",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Create a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication-service"
                ],
                "summary": "Sign up",
                "parameters": [
                    {
                        "description": "Signup data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateAccountRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateAccountResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request body",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "post": {
                "description": "Verify a user account with email verification code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication-service"
                ],
                "summary": "Verify Account",
                "parameters": [
                    {
                        "description": "Verification data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.VerifyAccountRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful verification (Wrapped in data envelope)",
                        "schema": {
                            "$ref": "#/definitions/dtos.VerifyAccountResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request or invalid code",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/players/character": {
            "get": {
                "description": "Retrieves the name and bio of the session player character",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players-service"
                ],
                "summary": "GetCharacterInfo",
                "responses": {
                    "200": {
                        "description": "Character info retrieved correctly",
                        "schema": {
                            "$ref": "#/definitions/dtos.CharacterInfoResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates the name and bio of the session player character",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players-service"
                ],
                "summary": "PatchCharacterInfo",
                "parameters": [
                    {
                        "description": "Character Info data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.PatchCharacterInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated correctly",
                        "schema": {
                            "$ref": "#/definitions/dtos.CharacterInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request body",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.AddSpriteCategoryRequest": {
            "type": "object",
            "required": [
                "category_name"
            ],
            "properties": {
                "category_name": {
                    "type": "string"
                }
            }
        },
        "dtos.CharacterInfoResponse": {
            "type": "object",
            "properties": {
                "category_sprites": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "character_bio": {
                    "type": "string"
                },
                "character_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateAccountRequestDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateAccountResponseDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dtos.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "instance": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dtos.LoginAccountRequestDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dtos.LoginAccountResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.PatchCharacterInfoRequest": {
            "type": "object",
            "properties": {
                "category_sprites": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "character_bio": {
                    "type": "string"
                },
                "character_name": {
                    "type": "string"
                }
            }
        },
        "dtos.SpriteCategoryListResponse": {
            "type": "object",
            "properties": {
                "category_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.SpriteCategoryResponse"
                    }
                }
            }
        },
        "dtos.SpriteCategoryResponse": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                }
            }
        },
        "dtos.SpriteResponse": {
            "type": "object",
            "properties": {
                "sprite_id": {
                    "type": "string"
                },
                "sprite_url": {
                    "type": "string"
                }
            }
        },
        "dtos.SpritesListResponse": {
            "type": "object",
            "properties": {
                "sprites_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.SpriteResponse"
                    }
                }
            }
        },
        "dtos.VerifyAccountRequestDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "dtos.VerifyAccountResponseDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "FeedTheRealm Core Service API",
	Description:      "This service manages all backend interactions for the feed the realm clients.\n\n⚠️ NOTE: All 2xx responses are wrapped in a 'Data envelope'.\nExample: { \"data\": { \"id\": \"123\", \"name\": \"Alice\" } }",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
