// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/signup": {
            "put": {
                "description": "Updates the name and bio of the session player character",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players-service"
                ],
                "summary": "UpdateCharacterInfo",
                "parameters": [
                    {
                        "description": "Character Info data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateCharacterInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated correctly",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateAccountResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request body",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Log in an existing user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication-service"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginAccountRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login",
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginAccountResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request body",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "post": {
                "description": "Verify a user account with email verification code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication-service"
                ],
                "summary": "Verify Account",
                "parameters": [
                    {
                        "description": "Verification data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.VerifyAccountRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful verification (Wrapped in data envelope)",
                        "schema": {
                            "$ref": "#/definitions/dtos.VerifyAccountResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request or invalid code",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/character/info": {
            "get": {
                "description": "Retrieves the name and bio of the session player character",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players-service"
                ],
                "summary": "GetCharacterInfo",
                "responses": {
                    "200": {
                        "description": "Character info retrieved correctly",
                        "schema": {
                            "$ref": "#/definitions/dtos.CharacterInfoResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/world": {
            "get": {
                "description": "Retrieves a paginated list of worlds",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "world-service"
                ],
                "summary": "GetWorldsList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pagination offset (starting index)",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (max 100)",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Worlds list retrieved correctly",
                        "schema": {
                            "$ref": "#/definitions/dtos.WorldsListResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Publishes a new world with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "world-service"
                ],
                "summary": "PublishWorld",
                "parameters": [
                    {
                        "description": "World Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.WorldRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Published correctly",
                        "schema": {
                            "$ref": "#/definitions/dtos.WorldResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request body",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/world/{id}": {
            "get": {
                "description": "Retrieves the name and data of the session player world",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "world-service"
                ],
                "summary": "GetWorld",
                "parameters": [
                    {
                        "type": "string",
                        "description": "World ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "World info retrieved correctly",
                        "schema": {
                            "$ref": "#/definitions/dtos.WorldResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CharacterInfoResponse": {
            "type": "object",
            "properties": {
                "character_bio": {
                    "type": "string"
                },
                "character_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateAccountRequestDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateAccountResponseDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dtos.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "instance": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dtos.LoginAccountRequestDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dtos.LoginAccountResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.UpdateCharacterInfoRequest": {
            "type": "object",
            "properties": {
                "character_bio": {
                    "type": "string"
                },
                "character_name": {
                    "type": "string"
                }
            }
        },
        "dtos.VerifyAccountRequestDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "dtos.VerifyAccountResponseDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                }
            }
        },
        "dtos.WorldRequest": {
            "type": "object",
            "properties": {
                "data": {},
                "file_name": {
                    "type": "string"
                }
            }
        },
        "dtos.WorldResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dtos.WorldsListResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "worlds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.WorldResponse"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "FeedTheRealm Core Service API",
	Description:      "This service manages all backend interactions for the feed the realm clients.\n\n⚠️ NOTE: All 2xx responses are wrapped in a 'Data envelope'.\nExample: { \"data\": { \"id\": \"123\", \"name\": \"Alice\" } }",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
