BEGIN;

CREATE TABLE IF NOT EXISTS gem_balances (
  user_id UUID PRIMARY KEY,
  gems INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMIT;
