BEGIN;

CREATE TABLE IF NOT EXISTS creator_balances (
  user_id UUID PRIMARY KEY,
  balance NUMERIC(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMIT;
