BEGIN;

CREATE TABLE IF NOT EXISTS gem_metrics (
  id SMALLINT PRIMARY KEY DEFAULT 1,
  gems_bought BIGINT NOT NULL DEFAULT 0,
  gems_spent BIGINT NOT NULL DEFAULT 0,
  gems_revenue NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMIT;
