BEGIN;

CREATE TABLE IF NOT EXISTS bundles (
    world_id UUID PRIMARY KEY,
    bundle_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
