#!/usr/bin/python3

import random
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import requests


def fetch_item_categories(server_url: str) -> List[Dict]:
    url = f"{server_url}/items/categories"
    resp = requests.get(url)
    if resp.status_code != 200:
        print(f"Failed to fetch item categories: {resp.status_code}")
        print(resp.text)
        return []
    data = resp.json().get("data", {})
    return data.get("categories", [])


def upload_item_sprite(server_url: str, file_path: Path, category_id: str) -> Optional[Dict]:
    url = f"{server_url}/assets/sprites/items"

    ext = file_path.suffix.lower()
    mime_type = "image/png" if ext == ".png" else "image/jpeg"

    try:
        with open(file_path, "rb") as f:
            files = {"sprite": (file_path.name, f, mime_type)}
            data = {"category_id": category_id}
            resp = requests.post(url, files=files, data=data)

        if resp.status_code in (200, 201):
            sprite = resp.json().get("data", {})
            print(f"✓ Uploaded sprite: {file_path.name} -> {sprite.get('id')}")
            return sprite
        else:
            print(
                f"✗ Failed to upload sprite {file_path.name}: {resp.status_code} - {resp.text[:200]}"
            )
            return None
    except Exception as e:
        print(f"✗ Error uploading sprite {file_path.name}: {e}")
        return None


def create_item(server_url: str, name: str, description: str, category_id: str, sprite_id: str) -> Optional[Dict]:
    url = f"{server_url}/items"
    payload = {
        "name": name,
        "description": description,
        "category_id": category_id,
        "sprite_id": sprite_id,
    }

    try:
        resp = requests.post(url, json=payload)
        if resp.status_code == 201:
            item = resp.json().get("data", {})
            print(f"✓ Created item: {item.get('name')} (ID: {item.get('id')})")
            return item
        else:
            print(
                f"✗ Failed to create item '{name}': {resp.status_code} - {resp.text[:200]}"
            )
            return None
    except Exception as e:
        print(f"✗ Error creating item '{name}': {e}")
        return None


def build_item_name_and_description(file_path: Path, category_name: str) -> Tuple[str, str]:
    base = file_path.stem
    base_clean = base.replace("_", " ").replace("-", " ")
    base_clean = " ".join(word.capitalize() for word in base_clean.split())
    if not base_clean:
        base_clean = "Unnamed Item"

    name = base_clean[:64]
    description = f"Autogenerated {category_name} item from asset {file_path.name}"[:256]
    return name, description


def seed_items_with_sprites(server_url: str, icons_root: Path, weapons_count: int = 5, armor_count: int = 5) -> None:
    """Seed 5 random Weapons and 5 random Armor items.

    icons_root should point to the base 6000FantasyIcons folder,
    e.g. client/Assets/6000FantasyIcons.
    """

    if not icons_root.exists() or not icons_root.is_dir():
        print(f"Error: {icons_root} is not a valid directory")
        return

    categories = fetch_item_categories(server_url)
    if not categories:
        print("No item categories found. Please create item categories first.")
        return

    categories_by_name: Dict[str, Dict] = {c["name"]: c for c in categories}

    print("\nAvailable item categories:")
    for idx, cat in enumerate(categories, 1):
        print(f"{idx}. {cat['name']} (ID: {cat['id']})")

    # Map logical category names to their subdirectories and desired counts
    category_config = {
        "Weapons": {
            "subdir": icons_root / "MedievalIcons" / "WeponMedieval",
            "count": weapons_count,
        },
        "Armor": {
            "subdir": icons_root / "MedievalIcons" / "ArmorMedieval",
            "count": armor_count,
        },
    }

    total_sprites = 0
    total_items = 0

    for cat_name, cfg in category_config.items():
        if cat_name not in categories_by_name:
            print(f"\nWarning: item category '{cat_name}' not found in API; skipping.")
            continue

        cat = categories_by_name[cat_name]
        cat_id = cat["id"]
        cat_dir: Path = cfg["subdir"]
        desired_count: int = cfg["count"]

        if not cat_dir.exists() or not cat_dir.is_dir():
            print(f"\nWarning: directory for '{cat_name}' not found at {cat_dir}; skipping.")
            continue

        all_files: List[Path] = sorted(cat_dir.glob("*.png"))
        if not all_files:
            print(f"\nWarning: no PNG files found for '{cat_name}' in {cat_dir}; skipping.")
            continue

        if desired_count <= 0 or desired_count >= len(all_files):
            chosen_files = all_files
        else:
            chosen_files = random.sample(all_files, desired_count)

        print(
            f"\nSeeding {len(chosen_files)} '{cat_name}' items from directory: {cat_dir}",
        )

        for file_path in chosen_files:
            sprite = upload_item_sprite(server_url, file_path, cat_id)
            if not sprite:
                continue
            total_sprites += 1

            sprite_id = sprite.get("id")
            item_name, item_desc = build_item_name_and_description(file_path, cat_name)

            item = create_item(server_url, item_name, item_desc, cat_id, sprite_id)
            if item:
                total_items += 1

    print("\n--- Seed Summary ---")
    print(f"Sprites uploaded: {total_sprites}")
    print(f"Items created:   {total_items}")


def main() -> None:
    if len(sys.argv) < 3:
        print(
            "Usage: python seed_items_with_sprites.py <server_url> <icons_root_path> [weapons_count] [armor_count]",
        )
        print(
            "Example: python seed_items_with_sprites.py http://localhost:8000 ./client/Assets/6000FantasyIcons 5 5",
        )
        return

    server_url = sys.argv[1].rstrip("/")
    # Ensure scheme
    if not server_url.startswith("http://") and not server_url.startswith("https://"):
        server_url = "http://" + server_url
    icons_root = Path(sys.argv[2])

    weapons_count = 5
    armor_count = 5

    if len(sys.argv) >= 4:
        try:
            weapons_count = int(sys.argv[3])
        except ValueError:
            print("Invalid weapons_count, using default 5.")

    if len(sys.argv) >= 5:
        try:
            armor_count = int(sys.argv[4])
        except ValueError:
            print("Invalid armor_count, using default 5.")

    seed_items_with_sprites(server_url, icons_root, weapons_count, armor_count)


if __name__ == "__main__":
    main()
