BEGIN;

ALTER TABLE models
ADD COLUMN IF NOT EXISTS created_by UUID;

ALTER TABLE items
ADD COLUMN IF NOT EXISTS created_by UUID;

ALTER TABLE cosmetics
ADD COLUMN IF NOT EXISTS created_by UUID;

COMMIT;
