BEGIN;

CREATE TABLE IF NOT EXISTS items_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE items
ADD COLUMN IF NOT EXISTS category_id UUID,

COMMIT;
