name: CI/CD for core-service
on:
  push:
  pull_request:
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and run docker-compose
        run: |
          docker compose up -d --build
      - name: Show running containers
        run: |
          docker ps -a
      - name: Run tests
        run: |
          docker compose exec -T app sh run_tests.sh